<!DOCTYPE html><html lang="ru"><head><script>window.currentUser = null;</script><script>window.rateUsdToNative = 65.69;</script><title itemprop="name">Перехват ошибок, &quot;try..catch&quot;</title><link href="pack/styles.ce210dd933f17ce8be6f.css" rel="stylesheet"><meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes, minimum-scale=1.0"><meta name="apple-mobile-web-app-capable" content="yes"><!-- chrome autotranslate is enabled only for "en" main version--><meta name="google" content="notranslate"><script>if (window.devicePixelRatio > 1) document.cookie = 'pixelRatio=' + window.devicePixelRatio + ';path=/;expires=Tue, 19 Jan 2038 03:14:07 GMT';</script><link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700%7COpen+Sans+Condensed:700&amp;subset=latin,latin-ext,cyrillic,cyrillic-ext" rel="stylesheet"><link rel="apple-touch-icon-precomposed" href="img/favicon/apple-touch-icon-precomposed.png"><link rel="canonical" href="https://learn.javascript.ru/exception"><meta name="msapplication-TileColor" content="#222A2C"><meta name="msapplication-TileImage" content="/img/favicon/tileicon.png"><link rel="icon" href="img/favicon/favicon.png"><meta itemprop="image" content="https://learn.javascript.ru/img/site_preview_ru_512x512.png"><meta property="og:title" content="Перехват ошибок, &quot;try..catch&quot;"><meta property="og:image" content="https://learn.javascript.ru/img/site_preview_ru_1200x630.png"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="fb:admins" content="100001562528165"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="Перехват ошибок, &quot;try..catch&quot;"><meta name="twitter:site" content="@iliakan"><meta name="twitter:creator" content="@iliakan"><meta name="twitter:image" content="https://learn.javascript.ru/img/site_preview_ru_512x512.png"><link rel="prev" href="eval.html"><link rel="next" href="oop.html"><script>window.GA_ID = "UA-2056213-16";</script><script>window.GTM_ID = 'GTM-WD2DZPG'</script><script>window.YANDEX_METRIKA_ID = 17649010;</script><script>window.GoogleAnalyticsObject="ga",window.ga=function(){window.ga.q.push(arguments)},window.ga.q=[],window.ga.l=Date.now(),ga("create",GA_ID,"auto"),window.GTM_ID&&ga("require",GTM_ID),window.currentUser?ga("set","&uid",currentUser.id):ga("set","anonymizeIp",!0),window.addEventListener("error",function(e){var r=(e.filename||e.errorUrl)+": "+(e.lineno||e.errorLine),n=e.stack||e.error&&e.error.stack;ga("send","exception",{exDescription:e.message+" "+r+" "+n,exFatal:!0})});</script><script src="https://www.google-analytics.com/analytics.js" async></script><script>ga('send', 'pageview');</script><script>window.metrika={reachGoal:function(){}},window.yandex_metrika_callbacks=[function(){try{window.metrika=new Ya.Metrika({id:YANDEX_METRIKA_ID,webvisor:!0,clickmap:!0,params:{user:window.currentUser&&window.currentUser.id}}),metrika.trackLinks({delay:150}),window.addEventListener("error",function(r){window.metrika.reachGoal("JSERROR",{src:(r.filename||r.errorUrl)+": "+(r.lineno||r.errorLine),stack:r.stack||r.error&&r.error.stack,message:r.message})})}catch(r){}}];</script><script src="http://mc.yandex.ru/metrika/watch.js" async></script><script>window.RECAPTCHA_ID = "6Lf9NyETAAAAACZlg-a9Us2SxvYbeVC1ROWaWv4O";</script><script src="pack/init.ce210dd933f17ce8be6f.js"></script><script src="pack/head.ce210dd933f17ce8be6f.js" defer></script><meta property="og:title" content="Перехват ошибок, &quot;try..catch&quot;"><meta property="og:type" content="article"><script src="pack/tutorial.ce210dd933f17ce8be6f.js" defer></script><script src="pack/footer.ce210dd933f17ce8be6f.js" defer></script></head><body class="no-icons"><script>window.fontTest();</script><div class="page-wrapper page-wrapper_sidebar_on"><!--[if lt IE 10]><div style="color:red;text-align:center">Извините, IE&lt;10 не поддерживается, пожалуйста используйте более новый браузер.</div><![endif]--><div class="sitetoolbar sitetoolbar_tutorial"><div class="sitetoolbar__content"><div class="sitetoolbar__logo-wrap"><a class="sitetoolbar__link sitetoolbar__link_logo" href="index.html"><img class="sitetoolbar__logo sitetoolbar__logo_normal" src="img/sitetoolbar__logo_ru.svg" width="171" alt="" role="presentation"/><img class="sitetoolbar__logo sitetoolbar__logo_small" src="img/sitetoolbar__logo_small_ru.svg" width="80" alt="" role="presentation"/><script>Array.prototype.forEach.call(document.querySelectorAll("img.sitetoolbar__logo"),function(e){let t=document.createElement("object");t.type="image/svg+xml",t.className=e.className,t.style.cssText="left:0;top:0;position:absolute",t.onload=function(){t.onload=null,e.style.visibility="hidden"},t.data=e.src,e.parentNode.insertBefore(t,e)});</script></a></div><div class="sitetoolbar__nav-toggle-wrap"><button class="sitetoolbar__nav-toggle" type="button"></button></div><nav class="sitetoolbar__sections"><ul class="sitetoolbar__sections-list"><li class="sitetoolbar__section sitetoolbar__section_current"><a class="sitetoolbar__link" href="index.html">Учебник</a></li><li class="sitetoolbar__section"><a class="sitetoolbar__link" href="courses.1.html">Курсы</a></li><li class="sitetoolbar__section"><a class="sitetoolbar__link" href="https://javascript.ru/forum/">Форум</a></li><li class="sitetoolbar__section"><a class="sitetoolbar__link" href="https://es5.javascript.ru">ES5</a></li><li class="sitetoolbar__section"><a class="sitetoolbar__link" href="quiz.html">Тесты знаний</a></li><li class="sitetoolbar__section"><a class="sitetoolbar__link" href="jobs.1.html">Стажировки</a></li><li class="sitetoolbar__section sitetoolbar__section_dropdown"><button class="sitetoolbar__dropdown-button" data-dropdown-toggler>Скринкасты</button><div class="sitetoolbar__dropdown-wrap"><div class="sitetoolbar__dropdown-body"><ul class="sitetoolbar__dropdown-items"><li class="sitetoolbar__dropdown-item"><a class="sitetoolbar__secondary-link sitetoolbar__dropdown-link" href="nodejs-screencast.html">Node.js</a></li><li class="sitetoolbar__dropdown-item"><a class="sitetoolbar__secondary-link sitetoolbar__dropdown-link" href="screencast/webpack.html">Webpack</a></li><li class="sitetoolbar__dropdown-item"><a class="sitetoolbar__secondary-link sitetoolbar__dropdown-link" href="screencast/gulp.html">Gulp 4</a></li><li class="sitetoolbar__dropdown-item"><a class="sitetoolbar__secondary-link sitetoolbar__dropdown-link" href="screencast/react.html">React.js</a></li><li class="sitetoolbar__dropdown-item"><a class="sitetoolbar__secondary-link sitetoolbar__dropdown-link" href="screencast/angular.html">Angular</a></li><li class="sitetoolbar__dropdown-item"><a class="sitetoolbar__secondary-link sitetoolbar__dropdown-link" href="screencast/git.html">Git</a></li></ul></div></div></li></ul></nav><div class="sitetoolbar__book-wrap"><a class="buy-book-button" href="ebook.1.html"><span class="buy-book-button__extra-text">Купить</span>EPUB/PDF</a></div><div class="sitetoolbar__login-wrap"><button class="sitetoolbar__login sitetoolbar__login_unready" data-action-login></button></div><div class="sitetoolbar__search-wrap"><div class="sitetoolbar__search-content"><form class="sitetoolbar__search" method="GET" action="http://learn.javascript.ru/search"><button class="sitetoolbar__search-toggle" type="button"></button><div class="sitetoolbar__search-input"><div class="text-input"><input class="text-input__control" autofocus="autofocus" name="query" placeholder="Искать на Javascript.ru" type="text"/></div><button class="sitetoolbar__find" type="submit">Найти</button></div></form></div></div></div><div class="tablet-menu"><div class="tablet-menu__line"><div class="tablet-menu__content"><select class="tablet-menu__nav input-select input-select input-select_small" onchange="if(this.value) window.location.href=this.value"><option value="/" selected>Учебник</option><option value="/courses">Курсы</option><option value="https://javascript.ru/forum/">Форум</option><option value="https://es5.javascript.ru">ES5</option><option value="/quiz">Тесты знаний</option><option value="/jobs">Стажировки</option></select></div></div><div class="tablet-menu__line"><div class="tablet-menu__content"><form class="tablet-menu-search" action="http://learn.javascript.ru/search/"><input class="tablet-menu-search__input" type="search" name="query" placeholder="Поиск в учебнике" required="required"/><button class="tablet-menu-search__button" type="submit" name="type" value="articles">Поиск</button></form></div></div><div class="tablet-menu__line"><div class="tablet-menu__content"><a class="map" href="tutorial/map.html" data-action="tutorial-map"><span class="map__text">Карта учебника</span></a></div></div><div class="tablet-menu__line"><div class="tablet-menu__content"><div class="share-icons"><span class="share-icons__title">Поделиться</span><a class="share share_tw" href="https://twitter.com/share?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_fb" href="https://www.facebook.com/sharer/sharer.php?s=100&amp;p%5Burl%5D=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_gp" href="https://plus.google.com/share?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_vk" href="https://vkontakte.ru/share.php?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a></div></div></div></div><progress class="tutorial-progress" data-sticky value="60" max="86" data-tooltip="Урок 60 из 86"></progress></div><div class="page page_sidebar_on page_inner_padding"><script>if(localStorage.noSidebar){document.querySelector(".page").classList.remove("page_sidebar_on");var pageWrapper=document.querySelector(".page-wrapper");pageWrapper&&pageWrapper.classList.remove("page-wrapper_sidebar_on")}setTimeout(function(){document.querySelector(".page").classList.add("page_sidebar-animation-on")},0);</script><div class="page__inner"><main class="main main_width-limit"><header class="main__header"><div class="main__header-inner"><ol class="breadcrumbs"><li class="breadcrumbs__item breadcrumbs__item_home" itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemref="breadcrumb-1"><a class="breadcrumbs__link" href="index.html" itemprop="url"><span class="breadcrumbs__hidden-text" itemprop="title">Учебник</span></a></li><li class="breadcrumbs__item" id="breadcrumb-1" itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemref="breadcrumb-2" itemprop="child"><a class="breadcrumbs__link" href="js.html" itemprop="url"><span itemprop="title">Язык JavaScript</span></a></li><li class="breadcrumbs__item" id="breadcrumb-2" itemscope itemtype="http://data-vocabulary.org/Breadcrumb" itemprop="child"><a class="breadcrumbs__link" href="js-misc.html" itemprop="url"><span itemprop="title">Некоторые другие возможности</span></a></li></ol><h1 class="main__header-title">Перехват ошибок, &quot;try..catch&quot;</h1></div></header><div class="content"><article class="formatted" itemscope itemtype="http://schema.org/TechArticle"><meta itemprop="name" content="Перехват ошибок, &quot;try..catch&quot;"><div itemprop="author" itemscope itemtype="http://schema.org/Person"><meta itemprop="email" content="iliakan@gmail.com"><meta itemprop="name" content="Ilya Kantor"></div><div itemprop="articleBody"><p>Как бы мы хорошо ни программировали, в коде бывают ошибки. Или, как их иначе называют, «исключительные ситуации» (исключения).</p>
<p>Обычно скрипт при ошибке, как говорят, «падает», с выводом ошибки в консоль.</p>
<p>Но бывают случаи, когда нам хотелось бы как-то контролировать ситуацию, чтобы скрипт не просто «упал», а сделал что-то разумное.</p>
<p>Для этого в JavaScript есть замечательная конструкция <code>try..catch</code>.</p>
<h2><a class="main__anchor" name="konstruktsiya-try-catch" href="exception.html#konstruktsiya-try-catch">Конструкция try…catch</a></h2><p>Конструкция <code>try..catch</code> состоит из двух основных блоков: <code>try</code>, и затем <code>catch</code>:</p>
<div data-trusted="1" class="code-example">
      <div class="codebox code-example__codebox">
        
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {

  // код ...

} catch (err) {

  // обработка ошибки

}</code></pre>
        </div>
      </div>
      
      </div><p>Работает она так:</p>
<ol>
<li>
<p>Выполняется код внутри блока <code>try</code>.</p>
</li>
<li>
<p>Если в нём ошибок нет, то блок <code>catch(err)</code> игнорируется, то есть выполнение доходит до конца <code>try</code> и потом прыгает через <code>catch</code>.</p>
</li>
<li>
<p>Если в нём возникнет ошибка, то выполнение <code>try</code> на ней прерывается, и управление прыгает в начало блока <code>catch(err)</code>.</p>
<p>При этом переменная <code>err</code> (можно выбрать и другое название) будет содержать объект ошибки с подробной информацией о произошедшем.</p>
</li>
</ol>
<p><strong>Таким образом, при ошибке в <code>try</code> скрипт не «падает», и мы получаем возможность обработать ошибку внутри <code>catch</code>.</strong></p>
<p>Посмотрим это на примерах.</p>
<ul>
<li>
<p>Пример без ошибок: при запуске сработают <code>alert</code> <code>(1)</code> и <code>(2)</code>:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:6,&quot;cols&quot;:[{&quot;start&quot;:33,&quot;end&quot;:40}]},{&quot;start&quot;:2,&quot;cols&quot;:[{&quot;start&quot;:33,&quot;end&quot;:40}]}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {

  alert('Начало блока try');  // (1) &lt;--

  // .. код без ошибок

  alert('Конец блока try');   // (2) &lt;--

} catch(e) {

  alert('Блок catch не получит управление, так как нет ошибок'); // (3)

}

alert(&quot;Потом код продолжит выполнение...&quot;);</code></pre>
        </div>
      </div>
      
      </div></li>
<li>
<p>Пример с ошибкой: при запуске сработают <code>(1)</code> и <code>(3)</code>:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:10,&quot;cols&quot;:[{&quot;start&quot;:67,&quot;end&quot;:74}]},{&quot;start&quot;:4,&quot;end&quot;:4},{&quot;start&quot;:2,&quot;cols&quot;:[{&quot;start&quot;:33,&quot;end&quot;:40}]}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {

  alert('Начало блока try');  // (1) &lt;--

  lalala; // ошибка, переменная не определена!

  alert('Конец блока try');  // (2)

} catch(e) {

  alert('Ошибка ' + e.name + &quot;:&quot; + e.message + &quot;\n&quot; + e.stack); // (3) &lt;--

}

alert(&quot;Потом код продолжит выполнение...&quot;);</code></pre>
        </div>
      </div>
      
      </div></li>
</ul>
<div class="important important_warn">
            <div class="important__header"><span class="important__type"><code>try..catch</code> подразумевает, что код синтаксически верен</span></div>
            <div class="important__content"><p>Если грубо нарушена структура кода, например не закрыта фигурная скобка или где-то стоит лишняя запятая, то никакой <code>try..catch</code> здесь не поможет. Такие ошибки называются <em>синтаксическими</em>, интерпретатор не может понять такой код.</p>
<p>Здесь же мы рассматриваем ошибки <em>семантические</em>, то есть происходящие в корректном коде, в процессе выполнения.</p>
</div></div>
<div class="important important_warn">
            <div class="important__header"><span class="important__type"><code>try..catch</code> работает только в синхронном коде</span></div>
            <div class="important__content"><p>Ошибку, которая произойдёт в коде, запланированном «на будущее», например в <code>setTimeout</code>, <code>try..catch</code> не поймает:</p>
<div data-trusted="1" class="code-example">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {
  setTimeout(function() {
    throw new Error(); // вылетит в консоль
  }, 1000);
} catch (e) {
  alert( &quot;не сработает&quot; );
}</code></pre>
        </div>
      </div>
      
      </div><p>На момент запуска функции, назначенной через <code>setTimeout</code>, этот код уже завершится, интерпретатор выйдет из блока <code>try..catch</code>.</p>
<p>Чтобы поймать ошибку внутри функции из <code>setTimeout</code>, и <code>try..catch</code> должен быть в той же функции.</p>
</div></div>
<h2><a class="main__anchor" name="obekt-oshibki" href="exception.html#obekt-oshibki">Объект ошибки</a></h2><p>В примере выше мы видим объект ошибки. У него есть три основных свойства:</p>
<dl>
<dt><code>name</code></dt>
<dd>Тип ошибки. Например, при обращении к несуществующей переменной: <code>&quot;ReferenceError&quot;</code>.</dd>
<dt><code>message</code></dt>
<dd>Текстовое сообщение о деталях ошибки.</dd>
<dt><code>stack</code></dt>
<dd>Везде, кроме IE8-, есть также свойство <code>stack</code>, которое содержит строку с информацией о последовательности вызовов, которая привела к ошибке.</dd>
</dl>
<p>В зависимости от браузера у него могут быть и дополнительные свойства, см. <a href="https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Error">Error в MDN</a> и <a href="http://msdn.microsoft.com/en-us/library/dww52sbt%28v=vs.85%29.aspx">Error в MSDN</a>.</p>
<h2><a class="main__anchor" name="primer-ispolzovaniya" href="exception.html#primer-ispolzovaniya">Пример использования</a></h2><p>В JavaScript есть встроенный метод <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse">JSON.parse(str)</a>, который используется для чтения JavaScript-объектов (и не только) из строки.</p>
<p>Обычно он используется для того, чтобы обрабатывать данные, полученные по сети, с сервера или из другого источника.</p>
<p>Мы получаем их и вызываем метод <code>JSON.parse</code>, вот так:</p>
<div data-trusted="1" class="code-example">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">var data = '{&quot;name&quot;:&quot;Вася&quot;, &quot;age&quot;: 30}'; // строка с данными, полученная с сервера

var user = JSON.parse(data); // преобразовали строку в объект

// теперь user -- это JS-объект с данными из строки
alert( user.name ); // Вася
alert( user.age ); // 30</code></pre>
        </div>
      </div>
      
      </div><p>Более детально формат JSON разобран в главе <a href="json.html">Формат JSON, метод toJSON</a>.</p>
<p><strong>В случае, если данные некорректны, <code>JSON.parse</code> генерирует ошибку, то есть скрипт «упадёт».</strong></p>
<p>Устроит ли нас такое поведение? Конечно нет!</p>
<p>Получается, что если вдруг что-то не так с данными, то посетитель никогда (если, конечно, не откроет консоль) об этом не узнает.</p>
<p>А люди очень-очень не любят, когда что-то «просто падает», без всякого объявления об ошибке.</p>
<p><strong>Бывают ситуации, когда без <code>try..catch</code> не обойтись, это – одна из таких.</strong></p>
<p>Используем <code>try..catch</code>, чтобы обработать некорректный ответ:</p>
<div data-trusted="1" class="code-example">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">var data = &quot;Has Error&quot;; // в данных ошибка

try {

  var user = JSON.parse(data); // &lt;-- ошибка при выполнении
  alert( user.name ); // не сработает

} catch (e) {
  // ...выполнится catch
  alert( &quot;Извините, в данных ошибка, мы попробуем получить их ещё раз&quot; );
  alert( e.name );
  alert( e.message );
}</code></pre>
        </div>
      </div>
      
      </div><p>Здесь в <code>alert</code> только выводится сообщение, но область применения гораздо шире: можно повторять запрос, можно предлагать посетителю использовать альтернативный способ, можно отсылать информацию об ошибке на сервер… Свобода действий.</p>
<h2><a class="main__anchor" name="generatsiya-svoih-oshibok" href="exception.html#generatsiya-svoih-oshibok">Генерация своих ошибок</a></h2><p>Представим на минуту, что данные являются корректным JSON… Но в этом объекте нет нужного свойства <code>name</code>:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:5,&quot;end&quot;:5}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">var data = '{ &quot;age&quot;: 30 }'; // данные неполны

try {

  var user = JSON.parse(data); // &lt;-- выполнится без ошибок
  alert( user.name ); // undefined

} catch (e) {
  // не выполнится
  alert( &quot;Извините, в данных ошибка&quot; );
}</code></pre>
        </div>
      </div>
      
      </div><p>Вызов <code>JSON.parse</code> выполнится без ошибок, но ошибка в данных есть. И, так как свойство <code>name</code> обязательно должно быть, то для нас это такие же некорректные данные, как и <code>&quot;Has Error&quot;</code>.</p>
<p>Для того, чтобы унифицировать и объединить обработку ошибок парсинга и ошибок в структуре, мы воспользуемся оператором <code>throw</code>.</p>
<h3><a class="main__anchor" name="operator-throw" href="exception.html#operator-throw">Оператор throw</a></h3><p>Оператор <code>throw</code> генерирует ошибку.</p>
<p>Синтаксис: <code>throw &lt;объект ошибки&gt;</code>.</p>
<p>Технически в качестве объекта ошибки можно передать что угодно, это может быть даже не объект, а число или строка, но всё же лучше, чтобы это был объект, желательно – совместимый со стандартным, то есть чтобы у него были как минимум свойства <code>name</code> и <code>message</code>.</p>
<p><strong>В качестве конструктора ошибок можно использовать встроенный конструктор: <code>new Error(message)</code> или любой другой.</strong></p>
<p>В JavaScript встроен ряд конструкторов для стандартных ошибок: <code>SyntaxError</code>, <code>ReferenceError</code>, <code>RangeError</code> и некоторые другие. Можно использовать и их, но только чтобы не было путаницы.</p>
<p>В данном случае мы используем конструктор <code>new SyntaxError(message)</code>. Он создаёт ошибку того же типа, что и <code>JSON.parse</code>.</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:6,&quot;end&quot;:8}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">var data = '{ &quot;age&quot;: 30 }'; // данные неполны

try {

  var user = JSON.parse(data); // &lt;-- выполнится без ошибок

  if (!user.name) {
    throw new SyntaxError(&quot;Данные некорректны&quot;);
  }

  alert( user.name );

} catch (e) {
  alert( &quot;Извините, в данных ошибка&quot; );
}</code></pre>
        </div>
      </div>
      
      </div><p>Получилось, что блок <code>catch</code> – единое место для обработки ошибок во всех случаях: когда ошибка выявляется при <code>JSON.parse</code> или позже.</p>
<h2><a class="main__anchor" name="probros-isklyucheniya" href="exception.html#probros-isklyucheniya">Проброс исключения</a></h2><p>В коде выше мы предусмотрели обработку ошибок, которые возникают при некорректных данных. Но может ли быть так, что возникнет какая-то другая ошибка?</p>
<p>Конечно, может! Код – это вообще мешок с ошибками, бывает даже так, что библиотеку выкладывают в открытый доступ, она там 10 лет лежит, её смотрят миллионы людей и на 11-й год находятся опаснейшие ошибки. Такова жизнь, таковы люди.</p>
<p>Блок <code>catch</code> в нашем примере предназначен для обработки ошибок, возникающих при некорректных данных. Если же в него попала какая-то другая ошибка, то вывод сообщения о «некорректных данных» будет дезинформацией посетителя.</p>
<p><strong>Ошибку, о которой <code>catch</code> не знает, он не должен обрабатывать.</strong></p>
<p>Такая техника называется <em>«проброс исключения»</em>: в <code>catch(e)</code> мы анализируем объект ошибки, и если он нам не подходит, то делаем <code>throw e</code>.</p>
<p>При этом ошибка «выпадает» из <code>try..catch</code> наружу. Далее она может быть поймана либо внешним блоком <code>try..catch</code> (если есть), либо «повалит» скрипт.</p>
<p>В примере ниже <code>catch</code> обрабатывает только ошибки <code>SyntaxError</code>, а остальные – выбрасывает дальше:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:16,&quot;end&quot;:20},{&quot;start&quot;:10,&quot;end&quot;:10}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">var data = '{ &quot;name&quot;: &quot;Вася&quot;, &quot;age&quot;: 30 }'; // данные корректны

try {

  var user = JSON.parse(data);

  if (!user.name) {
    throw new SyntaxError(&quot;Ошибка в данных&quot;);
  }

  blabla(); // произошла непредусмотренная ошибка

  alert( user.name );

} catch (e) {

  if (e.name == &quot;SyntaxError&quot;) {
    alert( &quot;Извините, в данных ошибка&quot; );
  } else {
    throw e;
  }

}</code></pre>
        </div>
      </div>
      
      </div><p>Заметим, что ошибка, которая возникла внутри блока <code>catch</code>, «выпадает» наружу, как если бы была в обычном коде.</p>
<p>В следующем примере такие ошибки обрабатываются ещё одним, «более внешним» <code>try..catch</code>:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:17,&quot;end&quot;:17},{&quot;start&quot;:8,&quot;end&quot;:10},{&quot;start&quot;:5,&quot;end&quot;:5}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">function readData() {
  var data = '{ &quot;name&quot;: &quot;Вася&quot;, &quot;age&quot;: 30 }';

  try {
    // ...
    blabla(); // ошибка!
  } catch (e) {
    // ...
    if (e.name != 'SyntaxError') {
      throw e; // пробрасываем
    }
  }
}

try {
  readData();
} catch (e) {
  alert( &quot;Поймал во внешнем catch: &quot; + e ); // ловим
}</code></pre>
        </div>
      </div>
      
      </div><p>В примере выше <code>try..catch</code> внутри <code>readData</code> умеет обрабатывать только <code>SyntaxError</code>, а внешний – все ошибки.</p>
<p>Без внешнего проброшенная ошибка «вывалилась» бы в консоль с остановкой скрипта.</p>
<h2><a class="main__anchor" name="oborachivanie-isklyucheniy" href="exception.html#oborachivanie-isklyucheniy">Оборачивание исключений</a></h2><p>И, для полноты картины – последняя, самая продвинутая техника по работе с ошибками. Она, впрочем, является стандартной практикой во многих объектно-ориентированных языках.</p>
<p>Цель функции <code>readData</code> в примере выше – прочитать данные. При чтении могут возникать разные ошибки, не только <code>SyntaxError</code>, но и, возможно, к примеру <code>URIError</code> (неправильное применение функций работы с URI) да и другие.</p>
<p>Код, который вызвал <code>readData</code>, хотел бы иметь либо результат, либо информацию об ошибке.</p>
<p>При этом очень важным является вопрос: обязан ли этот внешний код знать о всевозможных типах ошибок, которые могут возникать при чтении данных, и уметь перехватывать их?</p>
<p>Обычно внешний код хотел бы работать «на уровень выше», и получать либо результат, либо «ошибку чтения данных», при этом какая именно ошибка произошла – ему неважно. Ну, или, если будет важно, то хотелось бы иметь возможность это узнать, но обычно не требуется.</p>
<p>Это важнейший общий подход к проектированию – каждый участок функционала должен получать информацию на том уровне, который ему необходим.</p>
<p>Мы его видим везде в грамотно построенном коде, но не всегда отдаём себе в этом отчёт.</p>
<p>В данном случае, если при чтении данных происходит ошибка, то мы будем генерировать её в виде объекта <code>ReadError</code>, с соответствующим сообщением. А «исходную» ошибку на всякий случай тоже сохраним, присвоим в свойство <code>cause</code> (англ. – причина).</p>
<p>Выглядит это так:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:19,&quot;end&quot;:19}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">function ReadError(message, cause) {
  this.message = message;
  this.cause = cause;
  this.name = 'ReadError';
  this.stack = cause.stack;
}

function readData() {
  var data = '{ bad data }';

  try {
    // ...
    JSON.parse(data);
    // ...
  } catch (e) {
    // ...
    if (e.name == 'URIError') {
      throw new ReadError(&quot;Ошибка в URI&quot;, e);
    } else if (e.name == 'SyntaxError') {
      throw new ReadError(&quot;Синтаксическая ошибка в данных&quot;, e);
    } else {
      throw e; // пробрасываем
    }
  }
}

try {
  readData();
} catch (e) {
  if (e.name == 'ReadError') {
    alert( e.message );
    alert( e.cause ); // оригинальная ошибка-причина
  } else {
    throw e;
  }
}</code></pre>
        </div>
      </div>
      
      </div><p>Этот подход называют «оборачиванием» исключения, поскольку мы берём ошибки «более низкого уровня» и «заворачиваем» их в <code>ReadError</code>, которая соответствует текущей задаче.</p>
<h2><a class="main__anchor" name="sektsiya-finally" href="exception.html#sektsiya-finally">Секция finally</a></h2><p>Конструкция <code>try..catch</code> может содержать ещё один блок: <code>finally</code>.</p>
<p>Выглядит этот расширенный синтаксис так:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:4,&quot;cols&quot;:[{&quot;start&quot;:2,&quot;end&quot;:9}]},{&quot;start&quot;:2,&quot;cols&quot;:[{&quot;start&quot;:2,&quot;end&quot;:7}]},{&quot;start&quot;:0,&quot;cols&quot;:[{&quot;start&quot;:0,&quot;end&quot;:3}]}]">
      <div class="codebox code-example__codebox">
        
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {
   .. пробуем выполнить код ..
} catch(e) {
   .. перехватываем исключение ..
} finally {
   .. выполняем всегда ..
}</code></pre>
        </div>
      </div>
      
      </div><p>Секция <code>finally</code> не обязательна, но если она есть, то она выполняется всегда:</p>
<ul>
<li>после блока <code>try</code>, если ошибок не было,</li>
<li>после <code>catch</code>, если они были.</li>
</ul>
<p>Попробуйте запустить такой код?</p>
<div data-trusted="1" class="code-example">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {
  alert( 'try' );
  if (confirm('Сгенерировать ошибку?')) BAD_CODE();
} catch (e) {
  alert( 'catch' );
} finally {
  alert( 'finally' );
}</code></pre>
        </div>
      </div>
      
      </div><p>У него два варианта работы:</p>
<ol>
<li>Если вы ответите на вопрос «сгенерировать ошибку?» утвердительно, то <code>try -&gt; catch -&gt; finally</code>.</li>
<li>Если ответите отрицательно, то <code>try -&gt; finally</code>.</li>
</ol>
<p><strong>Секцию <code>finally</code> используют, чтобы завершить начатые операции при любом варианте развития событий.</strong></p>
<p>Например, мы хотим подсчитать время на выполнение функции <code>sum(n)</code>, которая должна возвратить сумму чисел от <code>1</code> до <code>n</code> и работает рекурсивно:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:12,&quot;end&quot;:14}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">function sum(n) {
  return n ? (n + sum(n - 1)) : 0;
}

var n = +prompt('Введите n?', 100);

var start = new Date();

try {
  var result = sum(n);
} catch (e) {
  result = 0;
} finally {
  var diff = new Date() - start;
}

alert( result ? result : 'была ошибка' );
alert( &quot;Выполнение заняло &quot; + diff );</code></pre>
        </div>
      </div>
      
      </div><p>Здесь секция <code>finally</code> гарантирует, что время будет подсчитано в любых ситуациях: при ошибке в <code>sum</code> или без неё.</p>
<p>Вы можете проверить это, запустив код с указанием <code>n=100</code> – будет без ошибки, <code>finally</code> выполнится после <code>try</code>, а затем с <code>n=100000</code> – будет ошибка из-за слишком глубокой рекурсии, управление прыгнет в <code>finally</code> после <code>catch</code>.</p>
<div class="important important_smart">
            <div class="important__header"><span class="important__type"><code>finally</code> и <code>return</code></span></div>
            <div class="important__content"><p>Блок <code>finally</code> срабатывает при <em>любом</em> выходе из <code>try..catch</code>, в том числе и <code>return</code>.</p>
<p>В примере ниже из <code>try</code> происходит <code>return</code>, но <code>finally</code> получает управление до того, как контроль возвращается во внешний код.</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:9,&quot;end&quot;:9}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">function func() {

  try {
    // сразу вернуть значение
    return 1;

  } catch (e) {
    /* ... */
  } finally {
    alert( 'finally' );
  }
}

alert( func() ); // сначала finally, потом 1</code></pre>
        </div>
      </div>
      
      </div><p>Если внутри <code>try</code> были начаты какие-то процессы, которые нужно завершить по окончании работы, то в <code>finally</code> это обязательно будет сделано.</p>
<p>Кстати, для таких случаев иногда используют <code>try..finally</code> вообще без <code>catch</code>:</p>
<div data-trusted="1" class="code-example">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">function func() {
  try {
    return 1;
  } finally {
    alert( 'Вызов завершён' );
  }
}

alert( func() ); // сначала finally, потом 1</code></pre>
        </div>
      </div>
      
      </div><p>В примере выше <code>try..finally</code> вообще не обрабатывает ошибки. Задача в другом: выполнить код при любом выходе из <code>try</code> – с ошибкой ли, без ошибок или через <code>return</code>.</p>
</div></div>
<h2><a class="main__anchor" name="poslednyaya-nadezhda-window-onerror" href="exception.html#poslednyaya-nadezhda-window-onerror">Последняя надежда: window.onerror</a></h2><p>Допустим, ошибка произошла вне блока <code>try..catch</code> или выпала из <code>try..catch</code> наружу, во внешний код. Скрипт упал.</p>
<p>Можно ли как-то узнать о том, что произошло? Да, конечно.</p>
<p>В браузере существует специальное свойство <code>window.onerror</code>, если в него записать функцию, то она выполнится и получит в аргументах сообщение ошибки, текущий URL и номер строки, откуда «выпала» ошибка.</p>
<p>Необходимо лишь позаботиться, чтобы функция была назначена заранее.</p>
<p>Например:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:1,&quot;end&quot;:4}]">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="показать" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-markup"><code class="language-markup">&lt;script&gt;
  window.onerror = function(message, url, lineNumber) {
    alert(&quot;Поймана ошибка, выпавшая в глобальную область!\n&quot; +
      &quot;Сообщение: &quot; + message + &quot;\n(&quot; + url + &quot;:&quot; + lineNumber + &quot;)&quot;);
  };

  function readData() {
    error(); // ой, что-то не так
  }

  readData();
&lt;/script&gt;</code></pre>
        </div>
      </div>
      
      </div><p>Как правило, роль <code>window.onerror</code> заключается не в том, чтобы оживить скрипт – скорее всего, это уже невозможно, а в том, чтобы отослать сообщение об ошибке на сервер, где разработчики о ней узнают.</p>
<p>Существуют даже специальные веб-сервисы, которые предоставляют скрипты для отлова и аналитики таких ошибок, например: <a href="https://errorception.com/">https://errorception.com/</a> или <a href="http://www.muscula.com/">http://www.muscula.com/</a>.</p>
<h2><a class="main__anchor" name="itogo" href="exception.html#itogo">Итого</a></h2><p>Обработка ошибок – большая и важная тема.</p>
<p>В JavaScript для этого предусмотрены:</p>
<ul>
<li>
<p>Конструкция <code>try..catch..finally</code> – она позволяет обработать произвольные ошибки в блоке кода.</p>
<p>Это удобно в тех случаях, когда проще сделать действие и потом разбираться с результатом, чем долго и нудно проверять, не упадёт ли чего.</p>
<p>Кроме того, иногда проверить просто невозможно, например <code>JSON.parse(str)</code> не позволяет «проверить» формат строки перед разбором. В этом случае блок <code>try..catch</code> необходим.</p>
<p>Полный вид конструкции:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:4,&quot;cols&quot;:[{&quot;start&quot;:2,&quot;end&quot;:9}]},{&quot;start&quot;:2,&quot;cols&quot;:[{&quot;start&quot;:2,&quot;end&quot;:7}]},{&quot;start&quot;:0,&quot;cols&quot;:[{&quot;start&quot;:0,&quot;end&quot;:3}]}]">
      <div class="codebox code-example__codebox">
        
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {
   .. пробуем выполнить код ..
} catch(e) {
   .. перехватываем исключение ..
} finally {
   .. выполняем всегда ..
}</code></pre>
        </div>
      </div>
      
      </div><p>Возможны также варианты <code>try..catch</code> или <code>try..finally</code>.</p>
</li>
<li>
<p>Оператор <code>throw err</code> генерирует свою ошибку, в качестве <code>err</code> рекомендуется использовать объекты, совместимые с встроенным типом <a href="http://javascript.ru/Error">Error</a>, содержащие свойства <code>message</code> и <code>name</code>.</p>
</li>
</ul>
<p>Кроме того, мы рассмотрели некоторые важные приёмы:</p>
<ul>
<li>
<p>Проброс исключения – <code>catch(err)</code> должен обрабатывать только те ошибки, которые мы рассчитываем в нём увидеть, остальные – пробрасывать дальше через <code>throw err</code>.</p>
<p>Определить, нужная ли это ошибка, можно, например, по свойству <code>name</code>.</p>
</li>
<li>
<p>Оборачивание исключений – функция, в процессе работы которой возможны различные виды ошибок, может «обернуть их» в одну общую ошибку, специфичную для её задачи, и уже её пробросить дальше. Чтобы при необходимости можно было подробно определить, что произошло, исходную ошибку обычно присваивают в свойство этой, общей. Обычно это нужно для логирования.</p>
</li>
<li>
<p>В <code>window.onerror</code> можно присвоить функцию, которая выполнится при любой «выпавшей» из скрипта ошибке. Как правило, это используют в информационных целях, например отправляют информацию об ошибке на специальный сервис.</p>
</li>
</ul>
</div></article><div class="tasks formatted"><h2 class="tasks__title" id="tasks"><a class="tasks__title-anchor main__anchor main__anchor main__anchor_noicon" href="exception.html#tasks">Задачи</a></h2><div class="task tasks__task"><div class="task__header"><div class="task__title-wrap"><h3 class="task__title"><a class="main__anchor" href="exception.html#finally-ili-prosto-kod" name="finally-ili-prosto-kod">Finally или просто код?</a></h3><a class="task__open-link" href="task/finally-or-code-after.html" target="_blank"></a></div><div class="task__header-note"><span class="task__importance" title="Насколько эта задача важна для освоения материала, от 1 до 5">важность: 5</span></div><div class="task__content"><p>Сравните два фрагмента кода.</p>
<ol>
<li>
<p>Первый использует <code>finally</code> для выполнения кода по выходу из <code>try..catch</code>:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:6,&quot;end&quot;:6}]">
      <div class="codebox code-example__codebox">
        
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {
  начать работу
  работать
} catch (e) {
  обработать ошибку
} finally {
  финализация: завершить работу
}</code></pre>
        </div>
      </div>
      
      </div></li>
<li>
<p>Второй фрагмент просто ставит очистку ресурсов за <code>try..catch</code>:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:6,&quot;end&quot;:6}]">
      <div class="codebox code-example__codebox">
        
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">try {
  начать работу
} catch (e) {
  обработать ошибку
}

финализация: завершить работу</code></pre>
        </div>
      </div>
      
      </div></li>
</ol>
<p>Нужно, чтобы код финализации всегда выполнялся при выходе из блока <code>try..catch</code> и, таким образом, заканчивал начатую работу. Имеет ли здесь <code>finally</code> какое-то преимущество или оба фрагмента работают одинаково?</p>
<p>Если имеет, то дайте пример когда код с <code>finally</code> работает верно, а без – неверно.</p>
<button class="task__solution" type="button">решение</button><div class="task__answer"><div class="task__answer-content"><p>Разница в поведении станет очевидной, если рассмотреть код внутри функции.</p>
<p>Поведение будет различным, если управление каким-то образом выпрыгнет из <code>try..catch</code>.</p>
<p>Например, <code>finally</code> сработает после <code>return</code>, но до передачи управления внешнему коду:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:3,&quot;end&quot;:3}]">
      <div class="codebox code-example__codebox">
        
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">function f() {
  try {
    ...
    return result;
  } catch (e) {
    ...
  } finally {
    очистить ресурсы
  }
}</code></pre>
        </div>
      </div>
      
      </div><p>Или же управление может выпрыгнуть из-за <code>throw</code>:</p>
<div data-trusted="1" class="code-example" data-highlight="[{&quot;start&quot;:7,&quot;end&quot;:7}]">
      <div class="codebox code-example__codebox">
        
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">function f() {
  try {
    ...

  } catch (e) {
    ...
    if(не умею обрабатывать эту ошибку) {
      throw e;
    }

  } finally {
    очистить ресурсы
  }
}</code></pre>
        </div>
      </div>
      
      </div><p>В этих случаях именно <code>finally</code> гарантирует выполнение кода до окончания работы <code>f</code>, просто код не будет вызван.</p>
</div><button class="close-button task__answer-close" type="button" title="закрыть"></button></div></div></div></div><div class="task tasks__task"><div class="task__header"><div class="task__title-wrap"><h3 class="task__title"><a class="main__anchor" href="exception.html#eval-kalkulyator-s-oshibkami" name="eval-kalkulyator-s-oshibkami">Eval-калькулятор с ошибками</a></h3><a class="task__open-link" href="http://learn.javascript.ru/task/eval-calculator-errors" target="_blank"></a></div><div class="task__header-note"><span class="task__importance" title="Насколько эта задача важна для освоения материала, от 1 до 5">важность: 5</span></div><div class="task__content"><p>Напишите интерфейс, который принимает математическое выражение (в <code>prompt</code>) и выводит результат его вычисления через <code>eval</code>.</p>
<p><strong>При ошибке нужно выводить сообщение и просить переввести выражение</strong>.</p>
<p>Ошибкой считается не только некорректное выражение, такое как <code>2+</code>, но и выражение, возвращающее <code>NaN</code>, например <code>0/0</code>.</p>
<a href="exception.html#" onclick="event.preventDefault(); runDemo(this)">Запустить демо</a><button class="task__solution" type="button">решение</button><div class="task__answer"><div class="task__answer-content"><p>Вычислить любое выражение нам поможет <code>eval</code>:</p>
<div data-trusted="1" class="code-example">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">alert( eval(&quot;2+2&quot;) ); // 4</code></pre>
        </div>
      </div>
      
      </div><p>Считываем выражение в цикле <code>while(true)</code>. Если при вычислении возникает ошибка – ловим её в <code>try..catch</code>.</p>
<p>Ошибкой считается, в том числе, получение <code>NaN</code> из <code>eval</code>, хотя при этом исключение не возникает. Можно бросить своё исключение в этом случае.</p>
<p>Код решения:</p>
<div data-trusted="1" class="code-example" data-demo="1">
      <div class="codebox code-example__codebox">
        
        <div class="toolbar codebox__toolbar">
          <div class="toolbar__tool">
            <a href="exception.html#" title="выполнить" data-action="run" class="toolbar__button toolbar__button_run"></a>
          </div>
          <div class="toolbar__tool">
            <a href="exception.html#" title="открыть в песочнице" target="_blank" data-action="edit" class="toolbar__button toolbar__button_edit"></a>
          </div>
        </div>
        <div class="codebox__code" data-code="1">
          <pre class="line-numbers language-javascript"><code class="language-javascript">var expr, res;

while (true) {
  expr = prompt(&quot;Введите выражение?&quot;, '2-');
  if (expr == null) break;

  try {
    res = eval(expr);
    if (isNaN(res)) {
      throw new Error(&quot;Результат неопределён&quot;);
    }

    break;
  } catch (e) {
    alert( &quot;Ошибка: &quot; + e.message + &quot;, повторите ввод&quot; );
  }
}

alert( res );</code></pre>
        </div>
      </div>
      
      </div></div><button class="close-button task__answer-close" type="button" title="закрыть"></button></div></div></div></div></div></div><div class="page__nav-wrap"><a class="page__nav page__nav_prev" href="eval.html" data-tooltip="Запуск кода из строки: eval"><span class="page__nav-text"><span class="page__nav-text-shortcut"></span></span><span class="page__nav-text-alternate">Предыдущий урок</span></a><a class="page__nav page__nav_next" href="oop.html" data-tooltip="ООП в функциональном стиле"><span class="page__nav-text"><span class="page__nav-text-shortcut"></span></span><span class="page__nav-text-alternate">Следующий урок</span></a></div><div class="article-tablet-foot tablet-only"><div class="article-tablet-foot__layout"><div class="share-icons"><span class="share-icons__title">Поделиться</span><a class="share share_tw" href="https://twitter.com/share?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_fb" href="https://www.facebook.com/sharer/sharer.php?s=100&amp;p%5Burl%5D=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_gp" href="https://plus.google.com/share?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_vk" href="https://vkontakte.ru/share.php?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a></div><div class="article-tablet-foot__map"><a class="map" href="tutorial/map.html" data-action="tutorial-map"><span class="map__text">Карта учебника</span></a></div></div></div><div class="banner-bottom"><div class="banner-bottom__text">Проводим <a href="courses.1.html">курсы по Javascript и фреймворкам</a>.</div><button class="banner-bottom__close" data-banner-close="Courses" data-banner-close-message="Эта информация больше не будет выводиться." title="не показывать"></button></div><script>"hideBannerCourses"in localStorage||(document.querySelector(".banner-bottom").style.display="flex");</script><div class="comments formatted" id="comments"><div class="comments__header"><h2 class="comments__header-title"><a href="exception.html#comments" name="comments">Комментарии</a></h2><div class="comments__read-before"><span class="comments__read-before-link">перед тем как писать…</span><div class="comments__read-before-popup"><div class="comments__read-before-popup-i"><ul><li>Приветствуются комментарии, содержащие дополнения и вопросы по статье, и ответы на них.</li><li>Для одной строки кода используйте тег <code>&lt;code&gt;</code>, для нескольких строк кода&nbsp;&mdash; тег <code>&lt;pre&gt;</code>, если больше 10 строк&nbsp;&mdash; ссылку на песочницу (<a href='http://plnkr.co/edit/?p=preview'>plnkr</a>, <a href='http://jsbin.com'>JSBin</a>, <a href='http://codepen.io'>codepen</a>…)</li><li>Если что-то непонятно в статье&nbsp;&mdash; пишите, что именно и с какого места.</li></ul></div></div></div></div></div><div id="disqus_thread"></div><script>var disqus_config = function() { if (!this.page) this.page = {}; Object.assign(this.page, {"url":"https:\/\/learn.javascript.ru\/exception","identifier":"\/exception"}); };</script><script>var disqus_shortname = "learnjavascriptru";</script><script>var disqus_enabled = true;</script></main></div><div class="sidebar page__sidebar sidebar sidebar_sticky-footer"><button class="sidebar__toggle" data-sidebar-toggle></button><a class="map" href="tutorial/map.html" data-action="tutorial-map" data-tooltip="Карта учебника"></a><div class="sidebar__inner"><div class="sidebar__content"><div class="sidebar__section"><h4 class="sidebar__section-title">Раздел</h4><nav class="sidebar__navigation"><ul class="sidebar__navigation-links"><li class="sidebar__navigation-link"><a class="sidebar__link" href="js-misc.html">Некоторые другие возможности</a></li></ul></nav></div><div class="sidebar__section"><h4 class="sidebar__section-title">Навигация по уроку</h4><nav class="sidebar__navigation"><ul class="sidebar__navigation-links"><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#konstruktsiya-try-catch">Конструкция try…catch</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#obekt-oshibki">Объект ошибки</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#primer-ispolzovaniya">Пример использования</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#generatsiya-svoih-oshibok">Генерация своих ошибок</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#probros-isklyucheniya">Проброс исключения</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#oborachivanie-isklyucheniy">Оборачивание исключений</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#sektsiya-finally">Секция finally</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#poslednyaya-nadezhda-window-onerror">Последняя надежда: window.onerror</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#itogo">Итого</a></li></ul></nav></div><div class="sidebar__section"><nav class="sidebar__navigation"><ul class="sidebar__navigation-links"><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#tasks">Задачи (2)</a></li><li class="sidebar__navigation-link"><a class="sidebar__link" href="exception.html#comments">Комментарии</a></li></ul></nav></div><div class="sidebar__section"><div class="sidebar__section-title">Поделиться</div><a class="share share_tw sidebar__share" href="https://twitter.com/share?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_fb sidebar__share" href="https://www.facebook.com/sharer/sharer.php?s=100&amp;p[url]=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_gp sidebar__share" href="https://plus.google.com/share?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a><a class="share share_vk sidebar__share" href="https://vkontakte.ru/share.php?url=http%3A%2F%2Flearn.javascript.ru%2Fexception"></a></div><div class="sidebar__section"><a class="sidebar__link" href="https://github.com/iliakan/javascript-tutorial-ru/blob/master/1-js/7-js-misc/5-exception/article.md">Редактировать на Github</a></div></div></div></div></div></div><div class="page-footer"><div class="page-footer__left"><ul class="page-footer__list"><li class="page-footer__item">©&nbsp;2007—2018&nbsp; Илья Кантор</li><li class="page-footer__item"><a class="page-footer__link" href="about.html#contact-us">связаться с нами</a></li><li class="page-footer__item"><a class="page-footer__link" href="terms.html">пользовательское соглашение</a></li><li class="page-footer__item"><a class="page-footer__link" href="privacy.html">политика конфиденциальности</a></li><li class="page-footer__item"><a class="page-footer__slack" href="http://slack.javascript.ru">slack-чат</a></li><li class="page-footer__item"><a class="page-footer__link" href="about.html">о проекте</a></li></ul></div><div class="page-footer__right"><ul class="page-footer__list"><li><a class="page-footer__link" rel="nofollow" href="http://github.com/iliakan/javascript-tutorial-ru">open source</a></li></ul></div></div></body></html>